### PR TITLE
BUG Prioritise same-level pages in OldPageRedirector

### LINKED ISSUE #2522: OldPageRedirector doesn't work properly with multiple pages having same URLSegment
We have multiple news list pages with same URLSegment and we noticed if we changed URLSegments of News (children of news listing pages) redirects didn't work.

I found a problem in OldPageRedirector::find_old_page. As it starts to look for old URL it doesn't necessarily start with ParentID=0 (root) as it's not requested and then it just picks first/random page (order by _Sort_ column) with the same URLSegment.

This lines:
```php
        if ($parent) {
            $pages = $pages->filter(array(
                'ParentID' => $parent->ID,
            ));
        }
```

should have a fallback to look on root level if no $parent is set:
```php
        if ($parent) {
            $pages = $pages->filter(array(
                'ParentID' => $parent->ID,
            ));
        } else {
            $pages = $pages->filter(array(
                'ParentID' => 0,
            ));
        }
```

I'm using SilverStripe v4.4.4, with Fluent 4.4. 

**Test case:**
1. Create page on root, Title "Test page" (URLSegment: "test-page") and publish it. In my case gets ID #19354, Sort=50
    _/test-page_
2. Create subpage on previously created page, Title "Goals" (URLSegment: "goals") and publish it. In my case gets ID #19355, Sort=1
    _/test-page/goals_
3. Create page on root, Title "Goals" (URLSegment: "goals") and publish it. In my case gets ID #19356, Sort=51
    _/goals_
4. Update URLSegment of "Goals" page (ID #19356) from previous line to "goals-new" and publish it
5. if you open _/goals_ you get redirected to _/test-page/goals/_ but it should redirect you to _/goals-new_

### PR DESCRIPTION
**Pull request by t3hn0**
Issue #2522 was merged into wrong branch (4) and we'd like to use this bugfix as soon as possible. 
I'm requesting new PR to make it available sooner for us.

Original description:
_Added option to pass integer ParentID=0 to OldPageRedirector::find_old_page to ensure search through nested pages from the root of SiteTree structure. Added new call of function and still offering fallback to old behaviour if first call returns false (fixed #2522)_

### CODE REVIEW

**Review by robbieaverill — APPROVED** [review]

**Comment by robbieaverill** [comment]
I've noticed that you've created this pull request from one of the "core branches" rather than a branch specifically intended for this pull request. This can cause problems if we ask you to target this PR at a different branch. No action is needed at the moment, this is for your information.

In the future please create a new branch for each individual pull request. See our [guide about contributing PRs](https://docs.silverstripe.org/en/4/contributing/code/#step-by-step-from-forking-to-sending-the-pull-request)

File: code/Controllers/OldPageRedirector.php [hunk 1]
```diff
@@ -29,7 +29,10 @@ public function onBeforeHTTPError404($request)
         $getvars = $request->getVars();
         unset($getvars['url']);
 
-        $page = static::find_old_page($params);
+        $page = self::find_old_page($params, 0);
```
Comment (patricknelson) [inline code/Controllers/OldPageRedirector.php:32]: Just FYI: It looks like this use of `self::` here instead of `static::` introduced a regression.  that was supposed to be addressed in #2478 (which itself was fixing #2438).
