### PR TITLE
FIX: Fixes #1054 By preventing errors in the CMS _only_.

### LINKED ISSUE #1054: Compare mode on History tab on draft-deleted object produces Internal Server Error
Hi,

I've deleted an item from the draft site. 
image

Whenever I go to the history tab, select compare mode and select two version that are there in the system, I get Internal Server Error. 

Corresponding log entry is following:

    [Thu Jul 17 13:05:17 2014] [error] [client 80.31.52.242] PHP Fatal error:  Call to a member function compareVersions() on a non-object in /home/sites/cnk1/mpp1cms/www2/cms/code/controllers/CMSPageHistoryController.php on line 381

It's not a big issue at this moment, but definitely does not make the site look very professional for our users.

The page I am trying to see is a subclass of Page, but nothing special really apart from a few extra fields.

### PR DESCRIPTION
**Pull request by phptek**
MINOR Boyscouting: Addition of missing braces, default return and missing types in @return annotation.

### CODE REVIEW

File: code/controllers/CMSPageHistoryController.php [hunk 1]
```diff
@@ -358,7 +358,7 @@ public function ShowVersionForm($versionID = null) {
 	/**
 	 * @param int $versionID
 	 * @param int $otherVersionID
-	 * @return Form
+	 * @return mixed Form|boolean|SS_HTTPResponse
```
Comment (dhensby) [inline code/controllers/CMSPageHistoryController.php]: this syntax is slightly wrong. it should either be `mixed` OR `Form|bool`

I don't think this ever returns a `SS_HTTPResponse` object because `Security::permissionFailure` throws an exception rather than returns anything?! IIRC...

Comment (kinglozzer) [inline code/controllers/CMSPageHistoryController.php]: `Security::permissionFailure()` does return a response, it’s `RequestHandler::httpError()` that doesn’t (this gets me every time!)

Comment (dhensby) [inline code/controllers/CMSPageHistoryController.php]: Ah! well - I don't think this should be returning a `SS_HTTPResponse`, should it??

Comment (phptek) [inline code/controllers/CMSPageHistoryController.php]: @dhensby `Security::permissionFailure()` returns an instance of `SS_HTTPResponse` ergo, returning `Security::permissionFailure()` on line 381 will mean that `CompareVersionsForm()` can return one of:

* A boolean
* An instance of `SS_HTTPResponse`
* An instance of `Form`

..personally I think multiple / mixed return types is crazy, but let's not over think this. This is how the method has been for years :-)

Comment (dhensby) [inline code/controllers/CMSPageHistoryController.php]: > let's not over think this. This is how the method has been for years

Aceepted, the syntax is still wrong, though - would you mind doing one of either `mixed` or the types it can return?

Comment (phptek) [inline code/controllers/CMSPageHistoryController.php]: @dhensby Explicitly adding a pipe-delimited list of the available return types _is permitted_ in phpDoc,:
 
>If you want to explicitly show multiple possible return types, list them pipe-delimited without spaces (e.g. "@return int|string").

https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.return.pkg.html

Comment (phptek) [inline code/controllers/CMSPageHistoryController.php]: Will do :-)

Comment (dhensby) [inline code/controllers/CMSPageHistoryController.php]: Thanks, really appreciate it!

Comment (assertchris) [inline code/controllers/CMSPageHistoryController.php]: In general I think it's better to switch to mixed when return types > 2...

Comment (phptek) [inline code/controllers/CMSPageHistoryController.php]: @assertchris @dhensby Done. Force-pushed. Over to you guys.

**Comment by dhensby** [comment]
Thanks
