### PR TITLE
FIX: Remove legacy fields which prevent page publish (fixes #2455)

### LINKED ISSUE #2455: SiteTree won't write new versions if only a field named 'Status' is changed
Please don’t ask how much time I wasted because of this bug 😭😂

```php
<?php

class MyPage extends Page
{
    private static $db = [
        'Status' => 'Varchar(255)'
    ];

    public function getCMSFields()
    {
        $this->beforeUpdateCMSFields(function (FieldList $fields) {
            $fields->addFieldToTab('Root.Main', TextField::create('Status'));
        });

        return parent::getCMSFields();
    }

    public function onAfterPublish()
    {
        die('you will never get this, a-la-la-la-la');
    }
}
```

Make changes to the value of status, `onAfterPublish()` won’t be called. The only time it’ll be called is if you also make a change to another field’s value as well. There are other issues this bug causes, but this is the easiest to reproduce.

The cause is this line: https://github.com/silverstripe/silverstripe-cms/blob/8a44071ec63c33abcec0d2901081114b30ae1907/code/Model/SiteTree.php#L1588.

I’m not sure if we should just remove that whole code block, but at the very least we should remove `Status` from the array as it’s no longer a field on `SiteTree` (it hasn’t been since 2.4). We should also remove `ToDo`, `VersionID` and `SaveCount`. 

## PRs
- https://github.com/silverstripe/silverstripe-cms/pull/3002

### PR DESCRIPTION
**Pull request by lozcalver**
## Description

This updates the list of fields which are ignored when deciding whether a new version (and therefore a new live version) should be created. Also made it configurable while I was there.

## Manual testing steps

Create a page type with a field `Status`, save and publish. Then change _only_ the status field and publish again: a new version won’t be written, and the live site won’t update. If you change status and something else, it will.

## Issues

- #2455

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [x] CI is green

### CODE REVIEW

File: code/Model/SiteTree.php [hunk 1]
```diff
@@ -1693,7 +1703,7 @@ protected function onBeforeWrite()
         }
 
         // Check to see if we've only altered fields that shouldn't affect versioning
-        $fieldsIgnoredByVersioning = ['HasBrokenLink', 'Status', 'HasBrokenFile', 'ToDo', 'VersionID', 'SaveCount'];
```
Comment (lozcalver) [inline code/Model/SiteTree.php:1695]: `HasBrokenFile` and `HasBrokenLink` are the only two fields that actually exist anymore.

I thought about changing `VersionID` to `Version` (which is what the field is now named), but that would be a behavioural change. It would also be a bit weird: changing the version number in the `SiteTree` table without writing a version would mean that `SiteTree` and `SiteTree_Versions` could end up out of sync.

File: code/Model/SiteTree.php [hunk 2]
```diff
@@ -301,6 +301,16 @@ class SiteTree extends DataObject implements PermissionProvider, i18nEntityProvi
         "Stage",  "Live"
     ];
 
+    /**
+     * Fields which, if changed on their own, won't cause a new version/live record to be created
+     * @var string[]
+     * @config
```
Comment (ChloeSartorelli) [inline code/Model/SiteTree.php]:
```suggestion
```

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
Overall looks good, thanks!

Can you please retarget this to `5.2`? That branch is still supported for bug fixes so it'd be good to get the fix in there instead of having to wait for 5.3.0 stable to release.

**Review by GuySartorelli — APPROVED** [review]
LGTM, works well locally.
