### PR TITLE
BUG Ensure all CMS forms include full ID / VersionID in path

### LINKED ISSUE #1510: Page urls are not bookmarkable
When editing a page that has a gridfield, the ID of the page being edited is stored in the session, and it makes it really hard to bookmark it.

`/admin/pages/edit/EditForm/field/Fields/item/3/edit`

If I go to another page and then visit this, it usually breaks.

Before 4.0 it would be great to fix these urls so that they matched the "edit" top level url.

Something like:

`/admin/pages/edit/show/11/EditForm/field/Fields/item/3/edit`

Where the edit page link is

`/admin/pages/edit/show/11`

And then we can dump the "store current page in session" dumbness that the cms relies on.

This story is a dependency of https://github.com/silverstripe/silverstripe-framework/issues/6141

PRs:
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/6781 (changelog notes)
 - [ ] https://github.com/silverstripe/silverstripe-cms/pull/1783 (new code)
 - [x] https://github.com/silverstripe/silverstripe-admin/pull/19 (removed code)
 - [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/418 (routing in react section)
 
 
Note: tim has been working on a 3.x fix at #1784

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #1510, meaning that we can now use formfield-actions in react sections.

Refactor tree operations into CMSMain; Increases complexity of CMSMain (unfortunately), but simplifies LeftAndMain by removing all tree-handling logic.

Cleanup of getEditForm() and various other aging code blocks.

Note: @timkung has been working on a 3.x version at https://github.com/silverstripe/silverstripe-cms/pull/1784

### CODE REVIEW

File: code/Controllers/CMSMain.php [hunk 1]
```diff
@@ -720,119 +1109,130 @@ public function getRecord($id, $versionID = null)
...
+        // Use <button> to allow full jQuery UI styling
+        $actionsFlattened = $actions->dataFields();
+        if ($actionsFlattened) {
+            /** @var FormAction $action */
+            foreach ($actionsFlattened as $action) {
+                $action->setUseButtonTag(true);
             }
+        }
 
-            if ($record->hasMethod('getCMSValidator')) {
```
Comment (chillu) [inline code/Controllers/CMSMain.php]: Hold on, it's still in `LeftAndMain->getEditForm()`, all good.

Comment (tractorcow) [inline code/Controllers/CMSMain.php]: This variable was actually unused (ide threw up warning).
